/*
 * Copyright 2017 Manuel Wrage
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.ivianuu.kommonextensions

inline fun Double.sin(): Double = Math.sin(this)
inline fun Double.cos(): Double = Math.cos(this)
inline fun Double.tan(): Double = Math.tan(this)
inline fun Double.asin(): Double = Math.asin(this)
inline fun Double.acos(): Double = Math.acos(this)
inline fun Double.atan(): Double = Math.atan(this)
inline fun Double.toRadians(): Double = Math.toRadians(this)
inline fun Double.toDegrees(): Double = Math.toDegrees(this)
inline fun Double.exp(): Double = Math.exp(this)
inline fun Double.log(): Double = Math.log(this)
inline fun Double.log10(): Double = Math.log10(this)
inline fun Double.sqrt(): Double = Math.sqrt(this)
inline fun Double.cbrt(): Double = Math.cbrt(this)
inline fun Double.IEEEremainder(divisor: Double): Double = Math.IEEEremainder(this, divisor)
inline fun Double.ceil(): Double = Math.ceil(this)
inline fun Double.floor(): Double = Math.floor(this)
inline fun Double.rint(): Double = Math.rint(this)
inline fun Double.atan2(x: Double): Double = Math.atan2(this, x)
inline fun Double.pow(exp: Double): Double = Math.pow(this, exp)
inline fun Double.round(): Long = Math.round(this)
inline fun Double.abs(): Double = Math.abs(this)
inline fun Double.ulp(): Double = Math.ulp(this)
inline fun Double.signum(): Double = Math.signum(this)
inline fun Double.sinh(): Double = Math.sinh(this)
inline fun Double.cosh(): Double = Math.cosh(this)
inline fun Double.tanh(): Double = Math.tanh(this)
inline fun Double.expm1(): Double = Math.expm1(this)
inline fun Double.log1p(): Double = Math.log1p(this)
inline fun Double.copySign(sign: Double): Double = Math.copySign(this, sign)
inline fun Double.exponent(): Int = Math.getExponent(this)
inline fun Double.next(direction: Double): Double = Math.nextAfter(this, direction)
inline fun Double.nextUp(): Double = Math.nextUp(this)
inline fun Double.scalb(scaleFactor: Int): Double = Math.scalb(this, scaleFactor)
inline fun Double.clamp(min: Double, max: Double): Double = Math.max(min, Math.min(this, max))

inline fun Float.sin(): Double = Math.sin(this.toDouble())
inline fun Float.cos(): Double = Math.cos(this.toDouble())
inline fun Float.tan(): Double = Math.tan(this.toDouble())
inline fun Float.asin(): Double = Math.asin(this.toDouble())
inline fun Float.acos(): Double = Math.acos(this.toDouble())
inline fun Float.atan(): Double = Math.atan(this.toDouble())
inline fun Float.toRadians(): Double = Math.toRadians(this.toDouble())
inline fun Float.toDegrees(): Double = Math.toDegrees(this.toDouble())
inline fun Float.exp(): Double = Math.exp(this.toDouble())
inline fun Float.log(): Double = Math.log(this.toDouble())
inline fun Float.log10(): Double = Math.log10(this.toDouble())
inline fun Float.sqrt(): Double = Math.sqrt(this.toDouble())
inline fun Float.cbrt(): Double = Math.cbrt(this.toDouble())
inline fun Float.IEEEremainder(divisor: Double): Double = Math.IEEEremainder(this.toDouble(), divisor)
inline fun Float.ceil(): Double = Math.ceil(this.toDouble())
inline fun Float.floor(): Double = Math.floor(this.toDouble())
inline fun Float.rint(): Double = Math.rint(this.toDouble())
inline fun Float.atan2(x: Double): Double = Math.atan2(this.toDouble(), x)
inline fun Float.pow(exp: Double): Double = Math.pow(this.toDouble(), exp)
inline fun Float.round(): Long = Math.round(this.toDouble())
inline fun Float.abs(): Double = Math.abs(this.toDouble())
inline fun Float.ulp(): Double = Math.ulp(this.toDouble())
inline fun Float.signum(): Double = Math.signum(this.toDouble())
inline fun Float.sinh(): Double = Math.sinh(this.toDouble())
inline fun Float.cosh(): Double = Math.cosh(this.toDouble())
inline fun Float.tanh(): Double = Math.tanh(this.toDouble())
inline fun Float.expm1(): Double = Math.expm1(this.toDouble())
inline fun Float.log1p(): Double = Math.log1p(this.toDouble())
inline fun Float.copySign(sign: Double): Double = Math.copySign(this.toDouble(), sign)
inline fun Float.exponent(): Int = Math.getExponent(this.toDouble())
inline fun Float.next(direction: Double): Double = Math.nextAfter(this.toDouble(), direction)
inline fun Float.nextUp(): Double = Math.nextUp(this.toDouble())
inline fun Float.scalb(scaleFactor: Int): Double = Math.scalb(this.toDouble(), scaleFactor)
inline fun Float.clamp(min: Double, max: Double): Double = Math.max(min, Math.min(this.toDouble(), max))

inline fun Int.sin(): Double = Math.sin(this.toDouble())
inline fun Int.cos(): Double = Math.cos(this.toDouble())
inline fun Int.tan(): Double = Math.tan(this.toDouble())
inline fun Int.asin(): Double = Math.asin(this.toDouble())
inline fun Int.acos(): Double = Math.acos(this.toDouble())
inline fun Int.atan(): Double = Math.atan(this.toDouble())
inline fun Int.toRadians(): Double = Math.toRadians(this.toDouble())
inline fun Int.toDegrees(): Double = Math.toDegrees(this.toDouble())
inline fun Int.exp(): Double = Math.exp(this.toDouble())
inline fun Int.log(): Double = Math.log(this.toDouble())
inline fun Int.log10(): Double = Math.log10(this.toDouble())
inline fun Int.sqrt(): Double = Math.sqrt(this.toDouble())
inline fun Int.cbrt(): Double = Math.cbrt(this.toDouble())
inline fun Int.IEEEremainder(divisor: Double): Double = Math.IEEEremainder(this.toDouble(), divisor)
inline fun Int.ceil(): Double = Math.ceil(this.toDouble())
inline fun Int.floor(): Double = Math.floor(this.toDouble())
inline fun Int.rint(): Double = Math.rint(this.toDouble())
inline fun Int.atan2(x: Double): Double = Math.atan2(this.toDouble(), x)
inline fun Int.pow(exp: Double): Double = Math.pow(this.toDouble(), exp)
inline fun Int.round(): Long = Math.round(this.toDouble())
inline fun Int.abs(): Double = Math.abs(this.toDouble())
inline fun Int.ulp(): Double = Math.ulp(this.toDouble())
inline fun Int.signum(): Double = Math.signum(this.toDouble())
inline fun Int.sinh(): Double = Math.sinh(this.toDouble())
inline fun Int.cosh(): Double = Math.cosh(this.toDouble())
inline fun Int.tanh(): Double = Math.tanh(this.toDouble())
inline fun Int.expm1(): Double = Math.expm1(this.toDouble())
inline fun Int.log1p(): Double = Math.log1p(this.toDouble())
inline fun Int.copySign(sign: Double): Double = Math.copySign(this.toDouble(), sign)
inline fun Int.exponent(): Int = Math.getExponent(this.toDouble())
inline fun Int.next(direction: Double): Double = Math.nextAfter(this.toDouble(), direction)
inline fun Int.nextUp(): Double = Math.nextUp(this.toDouble())
inline fun Int.scalb(scaleFactor: Int): Double = Math.scalb(this.toDouble(), scaleFactor)
inline fun Int.clamp(min: Double, max: Double): Double = Math.max(min, Math.min(this.toDouble(), max))

inline fun Long.sin(): Double = Math.sin(this.toDouble())
inline fun Long.cos(): Double = Math.cos(this.toDouble())
inline fun Long.tan(): Double = Math.tan(this.toDouble())
inline fun Long.asin(): Double = Math.asin(this.toDouble())
inline fun Long.acos(): Double = Math.acos(this.toDouble())
inline fun Long.atan(): Double = Math.atan(this.toDouble())
inline fun Long.toRadians(): Double = Math.toRadians(this.toDouble())
inline fun Long.toDegrees(): Double = Math.toDegrees(this.toDouble())
inline fun Long.exp(): Double = Math.exp(this.toDouble())
inline fun Long.log(): Double = Math.log(this.toDouble())
inline fun Long.log10(): Double = Math.log10(this.toDouble())
inline fun Long.sqrt(): Double = Math.sqrt(this.toDouble())
inline fun Long.cbrt(): Double = Math.cbrt(this.toDouble())
inline fun Long.IEEEremainder(divisor: Double): Double = Math.IEEEremainder(this.toDouble(), divisor)
inline fun Long.ceil(): Double = Math.ceil(this.toDouble())
inline fun Long.floor(): Double = Math.floor(this.toDouble())
inline fun Long.rint(): Double = Math.rint(this.toDouble())
inline fun Long.atan2(x: Double): Double = Math.atan2(this.toDouble(), x)
inline fun Long.pow(exp: Double): Double = Math.pow(this.toDouble(), exp)
inline fun Long.round(): Long = Math.round(this.toDouble())
inline fun Long.abs(): Double = Math.abs(this.toDouble())
inline fun Long.ulp(): Double = Math.ulp(this.toDouble())
inline fun Long.signum(): Double = Math.signum(this.toDouble())
inline fun Long.sinh(): Double = Math.sinh(this.toDouble())
inline fun Long.cosh(): Double = Math.cosh(this.toDouble())
inline fun Long.tanh(): Double = Math.tanh(this.toDouble())
inline fun Long.expm1(): Double = Math.expm1(this.toDouble())
inline fun Long.log1p(): Double = Math.log1p(this.toDouble())
inline fun Long.copySign(sign: Double): Double = Math.copySign(this.toDouble(), sign)
inline fun Long.exponent(): Int = Math.getExponent(this.toDouble())
inline fun Long.next(direction: Double): Double = Math.nextAfter(this.toDouble(), direction)
inline fun Long.nextUp(): Double = Math.nextUp(this.toDouble())
inline fun Long.scalb(scaleFactor: Int): Double = Math.scalb(this.toDouble(), scaleFactor)
inline fun Long.clamp(min: Double, max: Double): Double = Math.max(min, Math.min(this.toDouble(), max))